services:
  nginx:
    image: nginx:alpine3.18
    container_name: nginx
    env_file: ${DPSRV_HOME}/rc/secrets/nginx/nginx.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DPSRV_HOME}/rc/secrets/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DPSRV_HOME}/rc/secrets/nginx/conf.d/:/etc/nginx/conf.d/
      - ${DPSRV_HOME}/var/www/:/usr/share/nginx/html/
      - ${DPSRV_HOME}/var/log/nginx/:/var/log/nginx/
      - /etc/localtime:/etc/localtime:ro
    restart: always
