services:
  dpsrv-nginx:
    container_name: dpsrv-nginx-${tag:-latest}
    image: dpsrv/nginx:${tag:-latest}
    build: .
    hostname: $HOSTNAME.dpsrv.me
    env_file:
      - ${DPSRV_HOME}/rc/secrets/nginx/nginx.env
      - ${DPSRV_HOME}/rc/secrets/local/${HOSTNAME}/${HOSTNAME}.env
    ports:
      - "80"
      - "443"
    volumes:
      - ${DPSRV_HOME}/rc/secrets/nginx/nginx.conf:/etc/nginx/nginx.conf.init:ro
      - ${DPSRV_HOME}/rc/secrets/nginx/conf.d/:/etc/nginx/conf.init/:ro
      - ${DPSRV_HOME}/rc/secrets/letsencrypt/:/etc/letsencrypt/:ro
      - ${DPSRV_HOME}/srv/www/:/usr/share/nginx/html/:ro
      - ${DPSRV_HOME}/var/log/nginx/:/var/log/nginx/
      - /etc/localtime:/etc/localtime:ro
    command: ['nginx', '-g', 'daemon off;']
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
